In [2]:
import tensorflow as tf
width = tf.placeholder("int32", name='width')
height = tf.placeholder("int32", name='height')
area = tf.multiply(width, height, name='area')

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('area=',sess.run(area, feed_dict={width: 6, height: 8}))

area= 48


In [3]:
tf.summary.merge_all()
train_writer = tf.summary.FileWriter('log/arrea',sess.graph)

In [5]:
ts_X = tf.Variable([0.4,0.2,0.4])
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X=sess.run(ts_X)
    print(X)

[0.4 0.2 0.4]


In [6]:
print(X.shape)

(3,)


In [7]:
ts_X = tf.Variable([[0.4, 0.2, 0.4]])
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X = sess.run(ts_X)
    print(X)

[[0.4 0.2 0.4]]


In [8]:
print('shape:', X.shape)

shape: (1, 3)


In [9]:
W = tf.Variable([[-0.5, -0.2],
                 [-0.3,  0.4],
                 [-0.5,  0.2]])

In [10]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    W_array = sess.run(W)
    print(W_array)

[[-0.5 -0.2]
 [-0.3  0.4]
 [-0.5  0.2]]


In [11]:
print(W_array.shape)

(3, 2)


In [12]:
X = tf.Variable([[1., 1., 1.]])
W = tf.Variable([[-0.5, -0.2],
                 [-0.3,  0.4],
                 [-0.5,  0.2]])
XW = tf.matmul(X, W)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print(sess.run(XW))

[[-1.3  0.4]]


In [13]:
b = tf.Variable([[0.1, 0.2]])
XW = tf.Variable([[-1.3, 0.4]])
Sum = XW + b
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('Sum:')
    print(sess.run(Sum))

Sum:
[[-1.1999999  0.6      ]]


In [14]:
X = tf.Variable([[1., 1., 1.]])
W = tf.Variable([[-0.5, -0.2],
                 [-0.3,  0.4],
                 [-0.5,  0.2]])
b = tf.Variable([[0.1, 0.2]])
XWb = tf.matmul(X, W) + b
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('XWb:')
    print(sess.run(XWb))

XWb:
[[-1.1999999  0.6      ]]
